services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: note_app
      POSTGRES_USER: note_app
      POSTGRES_PASSWORD: note_app
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U note_app -d note_app']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
