services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: note_app
      MYSQL_USER: note_app
      MYSQL_PASSWORD: note_app
      MYSQL_ROOT_PASSWORD: note_app_root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'note_app',
          '-pnote_app',
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
